development:
  bucket: popupburlington
  access_key_id: AKIAIEWZLMVMNNNTH52A
  secret_access_key: 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

test:
  bucket: popupburlington
  access_key_id: AKIAIEWZLMVMNNNTH52A
  secret_access_key: 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

production:
  bucket: popupburlington
  access_key_id: AKIAIEWZLMVMNNNTH52A
  secret_access_key: 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